ALTER TABLE epad_file DROP COLUMN templateleveltype; 
ALTER TABLE epad_file ADD COLUMN templateleveltype varchar(10) NULL;
UPDATE epad_file set templateleveltype = 'image' WHERE filetype = 'Template' and templateleveltype is null;


CREATE TABLE IF NOT EXISTS `lexicon` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_MEANING` varchar(255) NOT NULL,
  `CODE_VALUE` varchar(100) NOT NULL,
  `description` varchar(2000) DEFAULT NULL,
  `PARENT_ID` int(11) DEFAULT NULL,
  `createdtime` timestamp,
  `updatetime` timestamp,
  `SCHEMA_DESIGNATOR` varchar(100) DEFAULT NULL,
  `SCHEMA_VERSION` varchar(8) DEFAULT NULL,
  `creator` varchar(128) DEFAULT NULL,
  `synonyms` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PRIMARY_KEY_D` (`ID`),
  UNIQUE KEY `UK_CODE_VALUE` (`CODE_VALUE`,`PARENT_ID`),
  KEY `IDX_CODE_MEANING_DESC_TDF3EEE11_082C_47CC_B9F3_8FF0BA6AA643` (`CODE_MEANING`),
  KEY `IDX_PARENT_ID_DESC_TDF3EEE11_082C_47CC_B9F3_8FF0BA6AA643` (`PARENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DELETE FROM lexicon WHERE SCHEMA_DESIGNATOR ='99EPAD';

LOCK TABLES `lexicon` WRITE;
INSERT INTO `lexicon`(CODE_MEANING,CODE_VALUE,description,PARENT_ID,createdtime,updatetime,SCHEMA_DESIGNATOR,SCHEMA_VERSION,creator,synonyms) VALUES
('Calculation','RID12780','Calculation',NULL,NULL,NULL,'RadLex','3.2','admin',NULL),
('Plugin','99EPADA2','Plugin',NULL,NULL,NULL,'99EPAD','1','admin',NULL),
('Area','99EPADA4','Area',NULL,NULL,NULL,'99EPAD','1','admin',NULL),
('StandardDeviation','99EPADA5','StandardDeviation',NULL,NULL,NULL,'99EPAD','1','admin',NULL),
('Min','99EPADA6','Min',NULL,NULL,NULL,'99EPAD','1','admin',NULL),
('Max','99EPADA7','Max',NULL,NULL,NULL,'99EPAD','1','admin',NULL),
('Double','99EPADD1','Double',NULL,NULL,NULL,'99EPAD','1','admin',NULL),
('Length','G-D7FE','Length',NULL,NULL,NULL,'SRT','NULL','admin',NULL),
('Mean','RID39224','Mean value calculation',NULL,NULL,NULL,'RadLex','3.12','admin',NULL),
('JJvector','99EPADP1','JJvector Plugin',NULL,NULL,NULL,'99EPAD','1','admin',NULL),
('Qifp3D','99EPADP2','Qifp3DFeatureExtraction Plugin',NULL,NULL,NULL,'99EPAD','1','admin',NULL),
('Proportion of pixels with intensity larger than','99EPADF1','Proportion of pixels with intensity larger than',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Entropy of histogram','99EPADF2','Entropy of histogram',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Peak Position','99EPADF3','Peak Position',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Lesion-Size','99EPADF4','Lesion-Size',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Major Axis','99EPADF5','Major Axis',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Minor Axis','99EPADF6','Minor Axis',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Lesion-Size','99EPADF7','Lesion-Size',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Major Axis','99EPADF8','Major Axis',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Minor Axis','99EPADF9','Minor Axis',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Histogram-min','99EPADF10','Histogram-min',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Histogram-max','99EPADF11','Histogram-max',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Histogram-median','99EPADF12','Histogram-median',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Histogram-mean','99EPADF13','Histogram-mean',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Histogram-std','99EPADF14','Histogram-std',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Histogram-skewness','99EPADF15','Histogram-skewness',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Histogram-kurtosis','99EPADF16','Histogram-kurtosis',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Histogram-bin','99EPADF17','Histogram-bin',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Difference In and Out','99EPADF18','Difference In and Out',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Variance','99EPADF19','Variance',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Gabor','99EPADF20','Gabor',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - window min','99EPADF21','Edge Sharpness - window min',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - window max','99EPADF22','Edge Sharpness - window max',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - window median','99EPADF23','Edge Sharpness - window median',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - window mean','99EPADF24','Edge Sharpness - window mean',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - window std','99EPADF25','Edge Sharpness - window std',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - window skewness','99EPADF26','Edge Sharpness - window skewness',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - window kurtosis','99EPADF27','Edge Sharpness - window kurtosis',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - scale min','99EPADF28','Edge Sharpness - scale min',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - scale max','99EPADF29','Edge Sharpness - scale max',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - scale median','99EPADF30','Edge Sharpness - scale median',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - scale mean','99EPADF31','Edge Sharpness - scale mean',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - scale std','99EPADF32','Edge Sharpness - scale std',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - scale skewness','99EPADF33','Edge Sharpness - scale skewness',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - scale kurtosis','99EPADF34','Edge Sharpness - scale kurtosis',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - window histogram','99EPADF35','Edge Sharpness - window histogram',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Sharpness - scale histrogram','99EPADF36','Edge Sharpness - scale histrogram',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Haar on Histogram','99EPADF37','Haar on Histogram',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Daube on Histogram','99EPADF38','Daube on Histogram',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Histogram on Edge','99EPADF39','Histogram on Edge',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Haar r=1/10R','99EPADF40','LAII Haar r=1/10R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Mean r=1/10R','99EPADF41','LAII Mean r=1/10R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Std r=1/10R','99EPADF42','LAII Std r=1/10R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Min r=1/10R','99EPADF43','LAII Min r=1/10R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Max r=1/10R','99EPADF44','LAII Max r=1/10R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII skewness r=1/10R','99EPADF45','LAII skewness r=1/10R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Haar r=1/8R','99EPADF46','LAII Haar r=1/8R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Mean r=1/8R','99EPADF47','LAII Mean r=1/8R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Std r=1/8R','99EPADF48','LAII Std r=1/8R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Min r=1/8R','99EPADF49','LAII Min r=1/8R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Max r=1/8R','99EPADF50','LAII Max r=1/8R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII skewness r=1/8R','99EPADF51','LAII skewness r=1/8R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Haar r=1/5R','99EPADF52','LAII Haar r=1/5R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Mean r=1/5R','99EPADF53','LAII Mean r=1/5R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Std r=1/5R','99EPADF54','LAII Std r=1/5R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Min r=1/5R','99EPADF55','LAII Min r=1/5R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Max r=1/5R','99EPADF56','LAII Max r=1/5R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII skewness r=1/5R','99EPADF57','LAII skewness r=1/5R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Haar r=1/3R','99EPADF58','LAII Haar r=1/3R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Mean r=1/3R','99EPADF59','LAII Mean r=1/3R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Std r=1/3R','99EPADF60','LAII Std r=1/3R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Min r=1/3R','99EPADF61','LAII Min r=1/3R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Max r=1/3R','99EPADF62','LAII Max r=1/3R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII skewness r=1/3R','99EPADF63','LAII skewness r=1/3R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Haar r=1/2R','99EPADF64','LAII Haar r=1/2R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Mean r=1/2R','99EPADF65','LAII Mean r=1/2R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Std r=1/2R','99EPADF66','LAII Std r=1/2R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Min r=1/2R','99EPADF67','LAII Min r=1/2R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII Max r=1/2R','99EPADF68','LAII Max r=1/2R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('LAII skewness r=1/2R','99EPADF69','LAII skewness r=1/2R',0,NULL,NULL,'99EPAD','1','admin',NULL),
('RDS Mean','99EPADF70','RDS Mean',0,NULL,NULL,'99EPAD','1','admin',NULL),
('RDS std','99EPADF71','RDS std',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Compactness','99EPADF72','Compactness',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Roughness','99EPADF73','Roughness',0,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Entropy','99EPADF74','Intensity Entropy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Harmonic Mean','99EPADF75','Intensity Harmonic Mean',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Mean','99EPADF76','Intensity Mean',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Median','99EPADF77','Intensity Median',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Mode','99EPADF78','Intensity Mode',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Trimmed Mean','99EPADF79','Intensity Trimmed Mean',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Inerquartile Difference ','99EPADF80','Intensity Inerquartile Difference ',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Mean Absolute Difference','99EPADF81','Intensity Mean Absolute Difference',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intenisty Range','99EPADF82','Intenisty Range',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Standard Deviation','99EPADF83','Intensity Standard Deviation',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Kurtosis','99EPADF84','Intensity Kurtosis',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Skewness','99EPADF85','Intensity Skewness',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Max','99EPADF86','Intensity Max',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Min','99EPADF87','Intensity Min',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Under -291 HU','99EPADF88','Intensity Under -291 HU',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Over -291 HU','99EPADF89','Intensity Over -291 HU',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Under -291 HU Percentage','99EPADF90','Intensity Under -291 HU Percentage',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Intensity Over -291 HU Percentage','99EPADF91','Intensity Over -291 HU Percentage',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Sphericity','99EPADF92','Sphericity',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Surface Area','99EPADF93','Surface Area',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Volume Area','99EPADF94','Volume Area',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Geometric Mean R = 1mm','99EPADF95','LVII Geometric Mean R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Harmonic Mean R = 1mm','99EPADF96','LVII Harmonic Mean R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mean R = 1mm','99EPADF97','LVII Mean R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Median R = 1mm','99EPADF98','LVII Median R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mode R = 1mm','99EPADF99','LVII Mode R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Trimmed Mean (25%) R = 1mm','99EPADF100','LVII Trimmed Mean (25%) R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Interquartile Difference R = 1mm','99EPADF101','LVII Interquartile Difference R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mean Absolute Difference R= 1mm','99EPADF102','LVII Mean Absolute Difference R= 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Standard Deviation R = 1mm','99EPADF103','LVII Standard Deviation R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Range R = 1mm','99EPADF104','LVII Range R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Kurtosis R = 1mm','99EPADF105','LVII Kurtosis R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Skewness R = 1mm','99EPADF106','LVII Skewness R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Max R = 1mm','99EPADF107','LVII Max R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Min R = 1mm','99EPADF108','LVII Min R = 1mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Geometric Mean R = 2mm','99EPADF109','LVII Geometric Mean R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Harmonic Mean R = 2mm','99EPADF110','LVII Harmonic Mean R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mean R = 2mm','99EPADF111','LVII Mean R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Median R = 2mm','99EPADF112','LVII Median R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mode R = 2mm','99EPADF113','LVII Mode R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Trimmed Mean (25%) R = 2mm','99EPADF114','LVII Trimmed Mean (25%) R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Interquartile Difference R = 2mm','99EPADF115','LVII Interquartile Difference R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mean Absolute Difference R= 2mm','99EPADF116','LVII Mean Absolute Difference R= 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Standard Deviation R = 2mm','99EPADF117','LVII Standard Deviation R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Range R = 2mm','99EPADF118','LVII Range R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Kurtosis R = 2mm','99EPADF119','LVII Kurtosis R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Skewness R = 2mm','99EPADF120','LVII Skewness R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Max R = 2mm','99EPADF121','LVII Max R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Min R = 2mm','99EPADF122','LVII Min R = 2mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Geometric Mean R = 3mm','99EPADF123','LVII Geometric Mean R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Harmonic Mean R = 3mm','99EPADF124','LVII Harmonic Mean R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mean R = 3mm','99EPADF125','LVII Mean R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Median R = 3mm','99EPADF126','LVII Median R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mode R = 3mm','99EPADF127','LVII Mode R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Trimmed Mean (25%) R = 3mm','99EPADF128','LVII Trimmed Mean (25%) R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Interquartile Difference R = 3mm','99EPADF129','LVII Interquartile Difference R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mean Absolute Difference R= 3mm','99EPADF130','LVII Mean Absolute Difference R= 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Standard Deviation R = 3mm','99EPADF131','LVII Standard Deviation R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Range R = 3mm','99EPADF132','LVII Range R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Kurtosis R = 3mm','99EPADF133','LVII Kurtosis R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Skewness R = 3mm','99EPADF134','LVII Skewness R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Max R = 3mm','99EPADF135','LVII Max R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Min R = 3mm','99EPADF136','LVII Min R = 3mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Geometric Mean R = 4mm','99EPADF137','LVII Geometric Mean R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Harmonic Mean R = 4mm','99EPADF138','LVII Harmonic Mean R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mean R = 4mm','99EPADF139','LVII Mean R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Median R = 4mm','99EPADF140','LVII Median R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mode R = 4mm','99EPADF141','LVII Mode R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Trimmed Mean (25%) R = 4mm','99EPADF142','LVII Trimmed Mean (25%) R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Interquartile Difference R = 4mm','99EPADF143','LVII Interquartile Difference R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mean Absolute Difference R= 4mm','99EPADF144','LVII Mean Absolute Difference R= 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Standard Deviation R = 4mm','99EPADF145','LVII Standard Deviation R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Range R = 4mm','99EPADF146','LVII Range R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Kurtosis R = 4mm','99EPADF147','LVII Kurtosis R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Skewness R = 4mm','99EPADF148','LVII Skewness R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Max R = 4mm','99EPADF149','LVII Max R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Min R = 4mm','99EPADF150','LVII Min R = 4mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Geometric Mean R = 5mm','99EPADF151','LVII Geometric Mean R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Harmonic Mean R = 5mm','99EPADF152','LVII Harmonic Mean R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mean R = 5mm','99EPADF153','LVII Mean R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Median R = 5mm','99EPADF154','LVII Median R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mode R = 5mm','99EPADF155','LVII Mode R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Trimmed Mean (25%) R = 5mm','99EPADF156','LVII Trimmed Mean (25%) R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Interquartile Difference R = 5mm','99EPADF157','LVII Interquartile Difference R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Mean Absolute Difference R= 5mm','99EPADF158','LVII Mean Absolute Difference R= 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Standard Deviation R = 5mm','99EPADF159','LVII Standard Deviation R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Range R = 5mm','99EPADF160','LVII Range R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Kurtosis R = 5mm','99EPADF161','LVII Kurtosis R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Skewness R = 5mm','99EPADF162','LVII Skewness R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Max R = 5mm','99EPADF163','LVII Max R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('LVII Min R = 5mm','99EPADF164','LVII Min R = 5mm',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Roughness Mean Radius','99EPADF165','Roughness Mean Radius',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Roughness Average Absolute difference','99EPADF166','Roughness Average Absolute difference',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Roughness Root Mean Squared','99EPADF167','Roughness Root Mean Squared',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Roughness Maximum Valley Depth','99EPADF168','Roughness Maximum Valley Depth',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Roughness Maximum Peak Height','99EPADF169','Roughness Maximum Peak Height',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Roughness Maximum Height of Profile','99EPADF170','Roughness Maximum Height of Profile',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Roughness Skewness','99EPADF171','Roughness Skewness',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Roughness Kurtosis','99EPADF172','Roughness Kurtosis',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Discarded','99EPADF173','Edge Discarded',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Harmonic Mean','99EPADF174','Edge Window Harmonic Mean',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Mean','99EPADF175','Edge Window Mean',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Median','99EPADF176','Edge Window Median',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Mode','99EPADF177','Edge Window Mode',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Trimmed Mean','99EPADF178','Edge Window Trimmed Mean',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Inerquartile Difference ','99EPADF179','Edge Window Inerquartile Difference ',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Mean Absolute Difference','99EPADF180','Edge Window Mean Absolute Difference',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Range','99EPADF181','Edge Window Range',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Standard Deviation','99EPADF182','Edge Window Standard Deviation',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Kurtosis','99EPADF183','Edge Window Kurtosis',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Skewness','99EPADF184','Edge Window Skewness',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Max','99EPADF185','Edge Window Max',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Window Min','99EPADF186','Edge Window Min',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Harmonic Mean','99EPADF187','Edge Scale Harmonic Mean',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Mean','99EPADF188','Edge Scale Mean',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Median','99EPADF189','Edge Scale Median',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Mode','99EPADF190','Edge Scale Mode',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Trimmed Mean','99EPADF191','Edge Scale Trimmed Mean',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Inerquartile Difference ','99EPADF192','Edge Scale Inerquartile Difference ',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Mean Absolute Difference','99EPADF193','Edge Scale Mean Absolute Difference',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Range','99EPADF194','Edge Scale Range',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Standard Deviation','99EPADF195','Edge Scale Standard Deviation',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Kurtosis','99EPADF196','Edge Scale Kurtosis',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Skewness','99EPADF197','Edge Scale Skewness',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Max','99EPADF198','Edge Scale Max',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Edge Scale Min','99EPADF199','Edge Scale Min',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean energy','99EPADF200','Haralick D=1mm mean energy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean entropy','99EPADF201','Haralick D=1mm mean entropy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean correlation','99EPADF202','Haralick D=1mm mean correlation',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean contrast','99EPADF203','Haralick D=1mm mean contrast',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean homogeneity','99EPADF204','Haralick D=1mm mean homogeneity',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean variance','99EPADF205','Haralick D=1mm mean variance',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean sum of means','99EPADF206','Haralick D=1mm mean sum of means',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean inertia','99EPADF207','Haralick D=1mm mean inertia',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean cluster shade','99EPADF208','Haralick D=1mm mean cluster shade',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean cluster tendency','99EPADF209','Haralick D=1mm mean cluster tendency',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean max probability','99EPADF210','Haralick D=1mm mean max probability',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm mean inverse variance','99EPADF211','Haralick D=1mm mean inverse variance',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean energy','99EPADF212','Haralick D=2mm mean energy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean entropy','99EPADF213','Haralick D=2mm mean entropy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean correlation','99EPADF214','Haralick D=2mm mean correlation',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean contrast','99EPADF215','Haralick D=2mm mean contrast',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean homogeneity','99EPADF216','Haralick D=2mm mean homogeneity',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean variance','99EPADF217','Haralick D=2mm mean variance',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean sum of means','99EPADF218','Haralick D=2mm mean sum of means',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean inertia','99EPADF219','Haralick D=2mm mean inertia',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean cluster shade','99EPADF220','Haralick D=2mm mean cluster shade',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean cluster tendency','99EPADF221','Haralick D=2mm mean cluster tendency',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean max probability','99EPADF222','Haralick D=2mm mean max probability',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm mean inverse variance','99EPADF223','Haralick D=2mm mean inverse variance',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean energy','99EPADF224','Haralick D=3mm mean energy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean entropy','99EPADF225','Haralick D=3mm mean entropy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean correlation','99EPADF226','Haralick D=3mm mean correlation',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean contrast','99EPADF227','Haralick D=3mm mean contrast',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean homogeneity','99EPADF228','Haralick D=3mm mean homogeneity',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean variance','99EPADF229','Haralick D=3mm mean variance',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean sum of means','99EPADF230','Haralick D=3mm mean sum of means',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean inertia','99EPADF231','Haralick D=3mm mean inertia',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean cluster shade','99EPADF232','Haralick D=3mm mean cluster shade',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean cluster tendency','99EPADF233','Haralick D=3mm mean cluster tendency',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean max probability','99EPADF234','Haralick D=3mm mean max probability',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm mean inverse variance','99EPADF235','Haralick D=3mm mean inverse variance',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std energy','99EPADF236','Haralick D=1mm std energy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std entropy','99EPADF237','Haralick D=1mm std entropy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std correlation','99EPADF238','Haralick D=1mm std correlation',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std contrast','99EPADF239','Haralick D=1mm std contrast',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std homogeneity','99EPADF240','Haralick D=1mm std homogeneity',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std variance','99EPADF241','Haralick D=1mm std variance',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std sum of means','99EPADF242','Haralick D=1mm std sum of means',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std inertia','99EPADF243','Haralick D=1mm std inertia',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std cluster shade','99EPADF244','Haralick D=1mm std cluster shade',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std cluster tendency','99EPADF245','Haralick D=1mm std cluster tendency',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std max probability','99EPADF246','Haralick D=1mm std max probability',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=1mm std inverse variance','99EPADF247','Haralick D=1mm std inverse variance',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std energy','99EPADF248','Haralick D=2mm std energy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std entropy','99EPADF249','Haralick D=2mm std entropy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std correlation','99EPADF250','Haralick D=2mm std correlation',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std contrast','99EPADF251','Haralick D=2mm std contrast',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std homogeneity','99EPADF252','Haralick D=2mm std homogeneity',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std variance','99EPADF253','Haralick D=2mm std variance',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std sum of means','99EPADF254','Haralick D=2mm std sum of means',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std inertia','99EPADF255','Haralick D=2mm std inertia',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std cluster shade','99EPADF256','Haralick D=2mm std cluster shade',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std cluster tendency','99EPADF257','Haralick D=2mm std cluster tendency',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std max probability','99EPADF258','Haralick D=2mm std max probability',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=2mm std inverse variance','99EPADF259','Haralick D=2mm std inverse variance',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std energy','99EPADF260','Haralick D=3mm std energy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std entropy','99EPADF261','Haralick D=3mm std entropy',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std correlation','99EPADF262','Haralick D=3mm std correlation',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std contrast','99EPADF263','Haralick D=3mm std contrast',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std homogeneity','99EPADF264','Haralick D=3mm std homogeneity',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std variance','99EPADF265','Haralick D=3mm std variance',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std sum of means','99EPADF266','Haralick D=3mm std sum of means',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std inertia','99EPADF267','Haralick D=3mm std inertia',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std cluster shade','99EPADF268','Haralick D=3mm std cluster shade',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std cluster tendency','99EPADF269','Haralick D=3mm std cluster tendency',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std max probability','99EPADF270','Haralick D=3mm std max probability',1,NULL,NULL,'99EPAD','1','admin',NULL),
('Haralick D=3mm std inverse variance','99EPADF271','Haralick D=3mm std inverse variance',1,NULL,NULL,'99EPAD','1','admin',NULL);
UNLOCK TABLES;

SET @jjvID = (SELECT MAX(ID) FROM lexicon where CODE_MEANING='JJvector');
UPDATE lexicon set PARENT_ID = @jjvID where PARENT_ID=0;

SET @qifp3dID = (SELECT MAX(ID) FROM lexicon where CODE_MEANING='Qifp3D');
UPDATE lexicon set PARENT_ID = @qifp3dID where PARENT_ID=1;





UPDATE dbversion SET version = '2.1';
commit;
