#!/bin/sh
### ====================================================================== ###
##                                                                          ##
##  dcm4che2/dcmdelete  Launch Script                                          ##
##                                                                          ##
### ====================================================================== ###

##moveSeriesToTrash not supported in the current dcm4chee

/home/pacs/dcm4chee-2.17.1-mysql/bin/twiddle.sh -uadmin -padmin invoke dcm4chee.archive:service=ContentEditService moveSeriesToTrash $1;
